[package]
name = "ac"
version = "0.1.0"
authors = ["Zed Tan <zed@shootbird.work>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
